# Common configuration for all Kafka nodes
x-kafka: &kafka
    image: local-kafka
    build:
      context: docker-build
    dns:
      - 8.8.8.8
      - 4.4.4.4
    restart: on-failure
    networks:
      - kafka-net

services:
  kafka-01:
    <<: *kafka
    container_name: "kafka-01"
    ports:
        - "29192:29192"
    volumes:
      - ./config/01/server.properties:/kafka/config/kraft/server.properties
      - ./data/01:/kafka-data/kraft-combined-logs

  kafka-02:
    <<: *kafka
    container_name: "kafka-02"
    ports:
        - "29292:29292"
    volumes:
      - ./config/02/server.properties:/kafka/config/kraft/server.properties
      - ./data/02:/kafka-data/kraft-combined-logs

  kafka-03:
    <<: *kafka
    container_name: "kafka-03"
    ports:
        - "29392:29392"
    volumes:
      - ./config/03/server.properties:/kafka/config/kraft/server.properties
      - ./data/03:/kafka-data/kraft-combined-logs

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8099:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=dev-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-01:9092,kafka-02:9092,kafka-03:9092
    networks:
      - kafka-net
      

networks:
    kafka-net:
        external: true
